/** Re-export shared balance config — single source of truth with server. */
export {
  MOVE,
  LOOK,
  THIRD_PERSON,
  SNIPER,
  VIEWMODEL,
  VIEW_BOB,
  VIEW_RECOIL,
  GUN_SWAY,
  SLIDE_GUN,
  PLAYER,
  DEATH,
  RANGE,
  rangeColX,
  rangeLaneCenter,
  rangeRowZ,
  rangeRowCount,
  buildRangeDummyHomes,
  WORLD,
  DUMMY,
  DEBUG,
  MATCH,
  type DummyBehaviorMode,
} from '@glint/shared'
